stages:
  - build
  - push
  - deploy

default:
  tags:
    - personal-runner

variables:
  CONTAINER_REGISTRY: cr.yandex
  CONTAINER_REPOSITORY: crprhackbsfen591qk9s

build-image:
  stage: build
  image: 
    name: gcr.io/kaniko-project/executor:v1.6.0-debug
    entrypoint: [""]
  script:
    - AUTH=$(echo -n json_key:"${REGISTRY_TOKEN_YC}"| base64| tr -d \\n)
    - |
      echo '{"auths": {"cr.yandex": {"auth": "'${AUTH}'"}}}' >> /kaniko/.docker/config.json
    - /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --no-push
      --tarPath=${CI_PROJECT_NAME}.tar
      --destination=${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG}
  artifacts:
    paths:
      - ${CI_PROJECT_NAME}.tar
    expire_in: 1 hour
  only:
    - main
    - tags
  except:
    - schedules

.push:
  stage: push
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [""]
  script:
    - crane auth login -u json_key -p "$(echo $REGISTRY_PASSWORD)" ${CONTAINER_REGISTRY}
    - crane push ${CI_PROJECT_NAME}.tar ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}
    - crane push ${CI_PROJECT_NAME}.tar ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG}
    - crane push ${CI_PROJECT_NAME}.tar ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/${CI_PROJECT_NAME}:latest
  needs:
    - build-image
  only:
    - main
    - tags

push-to-internal:
  extends: .push
  variables:
    REGISTRY_PASSWORD: $REGISTRY_TOKEN_YC
  needs: ["build-image"]

deploy-stage:
  stage: deploy
  image: foo4/qbec-builder:v0.1.5
  script:
    - mkdir ~/.kube
    - cp $KUBECONFIG_YC ~/.kube/config
    - kubectl config use-context stage-k8s-regional-cluster
    - qbec validate stage --root qbec/clock-dpl --vm:ext-str image_tag=$CI_COMMIT_TAG
    - qbec apply stage --root qbec/clock-dpl --vm:ext-str image_tag=$CI_COMMIT_TAG --wait --yes
  needs: 
    - push-to-internal
  only:
    - tags

deploy-prod:
  stage: deploy
  image: foo4/qbec-builder:v0.1.5
  script:
    - mkdir ~/.kube
    - cp $KUBECONFIG_YC ~/.kube/config
    - kubectl config use-context prod-k8s-regional-cluster
    - qbec validate prod --root qbec/clock-dpl --vm:ext-str image_tag=$CI_COMMIT_TAG
    - qbec apply prod --root qbec/clock-dpl --vm:ext-str image_tag=$CI_COMMIT_TAG --wait --yes
  needs: 
    - push-to-internal
  rules:
    - if: "$CI_COMMIT_TAG =~ /-prod$/"
  when: manual
